#!/usr/bin/env ruby-local-exec

oldrev, newrev = ARGV

def run(cmd)
  exit $?.exitstatus unless system "umask 002 & #{cmd}"
end

ENV['RACK_ENV'] ||= 'production'

bundler_args = ['--deployment', '--quiet', '--binstubs', '--shebang', 'ruby-local-exec']
bundler_args << '--without development:test'

run "bundle install #{bundler_args.join(' ')}"

tasks = []
tasks << 'db:migrate'

run "bundle exec rake #{tasks.join(' ')}" if tasks.any?

run 'git clean -x -f -- public/stylesheets public/javascripts'
